// Узбекские тексты страниц сайта: ключ — английский оригинал из content/*.ts (t3), значение — перевод.
// Юридические страницы (политика, условия, импрессум) и документация сюда намеренно не входят: их перевод готовит юрист; для них показывается английский.
export const UZ: Record<string, string> = {
 "Our Team": "Bizning jamoa",
 "A small team of engineers, designers and support specialists who build Firmspace AI and answer your questions every day.": "Firmspace AI ni yaratadigan va savollaringizga har kuni javob beradigan muhandislar, dizaynerlar va qo‘llab-quvvatlash mutaxassislaridan iborat kichik jamoa.",
 "CEO & Co-founder": "Bosh direktor va hammuassis",
 "Builds the vision and makes sure we solve real problems of small companies.": "Qarashni shakllantiradi va kichik kompaniyalarning haqiqiy muammolarini hal qilishimizni ta’minlaydi.",
 "CTO": "Texnik direktor",
 "Leads the platform architecture: performance, security and integrations.": "Platforma arxitekturasini boshqaradi: unumdorlik, xavfsizlik va integratsiyalar.",
 "Head of Design": "Dizayn rahbari",
 "Makes complex workflows feel simple on every screen size.": "Murakkab ish jarayonlarini har qanday ekran o‘lchamida oddiy qilib ko‘rsatadi.",
 "Senior Engineer": "Yetakchi muhandis",
 "Works on real-time messaging, telephony and mail synchronization.": "Real vaqtdagi xabarlar, telefoniya va pochta sinxronlashi ustida ishlaydi.",
 "Customer Success": "Mijozlar muvaffaqiyati",
 "Helps teams get started and get the most out of the CRM.": "Jamoalarga boshlashga va CRMdan maksimal foydalanishga yordam beradi.",
 "Marketing Lead": "Marketing rahbari",
 "Tells the story of Firmspace AI and listens to what customers need.": "Firmspace AI haqida hikoya qiladi va mijozlarga nima kerakligini tinglaydi.",
 "Careers": "Vakansiyalar",
 "We are growing. Join a friendly remote-first team and help thousands of companies work better with their customers.": "Biz o‘sib bormoqdamiz. Do‘stona masofaviy jamoaga qo‘shiling va minglab kompaniyalarga mijozlari bilan yaxshiroq ishlashga yordam bering.",
 "Why work with us": "Nima uchun biz bilan ishlash kerak",
 "Remote-first with flexible hours": "Masofaviy ish va moslashuvchan jadval",
 "Learning budget and paid conferences": "O‘qish byudjeti va to‘lanadigan konferensiyalar",
 "30 days of paid vacation": "30 kunlik pullik ta’til",
 "Modern stack: Next.js, TypeScript, MongoDB": "Zamonaviy stek: Next.js, TypeScript, MongoDB",
 "Open positions": "Ochiq vakansiyalar",
 "Apply": "Ariza berish",
 "Senior Frontend Engineer": "Katta frontend-muhandis",
 "Remote · Full-time": "Masofaviy · To‘liq stavka",
 "Backend Engineer (Node.js)": "Backend-muhandis (Node.js)",
 "Product Designer": "Mahsulot dizayneri",
 "Berlin or remote · Full-time": "Berlin yoki masofaviy · To‘liq stavka",
 "Customer Support Specialist": "Mijozlarni qo‘llab-quvvatlash mutaxassisi",
 "Remote · Part-time": "Masofaviy · Qisman band",
 "Support / FAQ": "Yordam / Savollar",
 "Answers to the questions we hear most often. Can't find yours? Write to us — we reply within one business day.": "Eng ko‘p so‘raladigan savollarga javoblar. O‘zingiznikini topmadingizmi? Bizga yozing — bir ish kuni ichida javob beramiz.",
 "Contact support": "Yordamga murojaat",
 "How do I create an account?": "Hisobni qanday yarataman?",
 "Press Sign Up in the top right corner, choose Company or Personal, fill in the form and confirm. You can start using the CRM right away.": "Yuqori o‘ng burchakdagi «Ro‘yxatdan o‘tish» tugmasini bosing, «Kompaniya» yoki «Shaxsiy» ni tanlang, shaklni to‘ldiring va tasdiqlang. CRMdan darhol foydalanishni boshlashingiz mumkin.",
 "Is there a free plan?": "Bepul tarif bormi?",
 "Yes, but a limited one: Free covers one user with the sales pipeline and tasks. The team part — employees and knowledge base, the feed and the calendar — starts with Standard at €20 a month (up to 50 users). Chat with customers, documents, finance, marketing, ads, automation and the AI assistant come with Professional at €53 a month, which also removes the user limit.": "Ha, lekin cheklangan: Bepul tarif savdo voronkasi va vazifalar bilan bitta foydalanuvchini qamrab oladi. Jamoa qismi — xodimlar va bilimlar bazasi, lenta va kalendar — Standart tarifdan (oyiga 20 €, 50 tagacha foydalanuvchi) boshlanadi. Mijozlar bilan chat, hujjatlar, moliya, marketing, reklama, avtomatlashtirish va SI yordamchi oyiga 53 € turadigan Professional tarifda, u foydalanuvchilar chegarasini ham olib tashlaydi.",
 "Can I change or cancel my plan?": "Tarifni o‘zgartirish yoki bekor qilish mumkinmi?",
 "Yes, at any time in Upgrade Your Plan. The change applies from the next billing period.": "Ha, istalgan vaqtda «Tarifni yangilash» bo‘limida. O‘zgarish keyingi hisob davridan boshlab kuchga kiradi.",
 "How do I connect Telegram, Viber or a phone number?": "Telegram, Viber yoki telefon raqamini qanday ulayman?",
 "Open Settings → Integration, choose the channel, enter the key from the provider and press Connect. Step-by-step guides are in the Documentation.": "Sozlamalar → Integratsiya bo‘limini oching, kanalni tanlang, provayderdan olingan kalitni kiriting va «Ulash» tugmasini bosing. Bosqichma-bosqich qo‘llanmalar Hujjatlarda.",
 "My mailbox will not connect. What should I do?": "Pochta qutim ulanmayapti. Nima qilay?",
 "Gmail, iCloud and Yahoo need an app password instead of your account password. Create one in your account security settings and use it in Web Mails.": "Gmail, iCloud va Yahoo uchun hisob parolingiz o‘rniga ilova paroli kerak. Uni hisobingiz xavfsizlik sozlamalarida yarating va Veb-pochtada foydalaning.",
 "Is my data safe?": "Ma’lumotlarim xavfsizmi?",
 "Data is transferred over HTTPS, passwords are hashed, and access keys of connected services are stored encrypted.": "Ma’lumotlar HTTPS orqali uzatiladi, parollar xeshlanadi, ulangan xizmatlarning kirish kalitlari shifrlangan holda saqlanadi.",
 "Can I use the CRM on my phone?": "CRMdan telefonda foydalansa bo‘ladimi?",
 "Yes. The interface adapts to phones and tablets, and calls and chats work in the mobile browser.": "Ha. Interfeys telefon va planshetlarga moslashadi, qo‘ng‘iroqlar va chatlar mobil brauzerda ishlaydi.",
 "How do I export my data?": "Ma’lumotlarimni qanday eksport qilaman?",
 "Contact support and we will send you an export of your contacts, companies and deals.": "Yordamga murojaat qiling — kontaktlar, kompaniyalar va bitimlaringiz eksportini yuboramiz.",
 "Features": "Imkoniyatlar",
 "Everything a growing company needs to work with customers, in one place.": "O‘sib borayotgan kompaniyaga mijozlar bilan ishlash uchun kerak bo‘lgan hamma narsa bir joyda.",
 "Deals pipeline": "Bitimlar voronkasi",
 "Kanban board with custom stages, drag and drop, comments and activity history.": "O‘zingiz belgilagan bosqichlar, sudrab o‘tkazish, izohlar va faollik tarixi bilan kanban doskasi.",
 "Contacts and companies": "Kontaktlar va kompaniyalar",
 "Complete cards with notes, links between people and companies, and search.": "Izohlar, odamlar va kompaniyalar o‘rtasidagi bog‘lanishlar hamda qidiruv bilan to‘liq kartochkalar.",
 "Tasks and calendar": "Vazifalar va kalendar",
 "Deadlines, reminders and a shared company calendar with week and month views.": "Muddatlar, eslatmalar va hafta hamda oy ko‘rinishlari bilan umumiy kompaniya kalendari.",
 "Unified inbox": "Yagona pochta qutisi",
 "Telegram, Viber, Messenger, SMS and website chat answered from one page.": "Telegram, Viber, Messenger, SMS va veb-sayt chati — bitta sahifadan javob beriladi.",
 "Calls in the browser": "Brauzerda qo‘ng‘iroqlar",
 "Call customers and receive calls through Twilio with a full call log.": "Twilio orqali mijozlarga qo‘ng‘iroq qiling va qo‘ng‘iroqlarni qabul qiling, to‘liq qo‘ng‘iroqlar jurnali bilan.",
 "Web mail": "Veb-pochta",
 "Gmail, Outlook, iCloud, Yahoo or any IMAP mailbox with drafts, stars and search.": "Gmail, Outlook, iCloud, Yahoo yoki istalgan IMAP pochta qutisi — qoralamalar, belgilar va qidiruv bilan.",
 "Automation": "Avtomatlashtirish",
 "Rules that react to stages, variables and constants — fewer manual steps.": "Bosqichlar, o‘zgaruvchilar va doimiylarga javob beradigan qoidalar — qo‘lda bajariladigan qadamlar kamroq.",
 "Marketing tools": "Marketing vositalari",
 "Campaigns, ads, segments and templates with results in one table.": "Kampaniyalar, reklama, segmentlar va shablonlar, natijalar bitta jadvalda.",
 "Inventory management": "Ombor boshqaruvi",
 "Stock, sales, transfers and write-offs, connected to your customers.": "Zaxira, sotuvlar, ko‘chirishlar va hisobdan chiqarishlar mijozlaringiz bilan bog‘langan.",
 "Referral program": "Referal dasturi",
 "Recommend Firmspace AI to other companies and get a free month for every company that subscribes.": "Firmspace AI ni boshqa kompaniyalarga tavsiya qiling va obuna bo‘lgan har bir kompaniya uchun bepul bir oy oling.",
 "How it works": "Qanday ishlaydi",
 "Share your link": "Havolangizni ulashing",
 "Send your personal link to a colleague, partner or client.": "Shaxsiy havolangizni hamkasb, hamkor yoki mijozga yuboring.",
 "They subscribe": "Ular obuna bo‘ladi",
 "The company signs up and chooses the Standard or Professional plan.": "Kompaniya ro‘yxatdan o‘tadi va Standart yoki Professional tarifni tanlaydi.",
 "You both win": "Ikkalangiz ham yutasiz",
 "You get one free month, and the new company gets 10% off its first year.": "Siz bir oy bepul olasiz, yangi kompaniya esa birinchi yilga 10% chegirma oladi.",
 "Your referral link": "Referal havolangiz",
 "Copy link": "Havolani nusxalash",
 "Copied!": "Nusxalandi!",
 "Sign in to get your personal link. Rewards are credited after the first payment of the invited company.": "Shaxsiy havolangizni olish uchun tizimga kiring. Mukofotlar taklif qilingan kompaniyaning birinchi to‘lovidan keyin hisoblanadi.",
 "About us": "Biz haqimizda",
 "Firmspace AI brings customer relationships, team work, projects and accounting into one cabinet. We build it for small and medium businesses — those where one person often does several jobs at once.": "Firmspace AI mijozlar bilan munosabatlar, jamoaviy ish, loyihalar va buxgalteriyani bitta kabinetga birlashtiradi. Biz uni kichik va o‘rta biznes uchun yaratamiz — bir kishi ko‘pincha bir vaqtning o‘zida bir nechta ishni bajaradigan biznes uchun.",
 "Our team at work": "Jamoamiz ish joyida",
 "We collect in one place what is usually scattered across five programs: the deal pipeline, conversations with customers, tasks and the calendar, quotes, orders, invoices and reports. One login, one set of data, one team.": "Odatda beshta dasturga tarqalgan narsani bir joyga yig‘amiz: bitimlar voronkasi, mijozlar bilan suhbatlar, vazifalar va kalendar, takliflar, buyurtmalar, hisob-fakturalar va hisobotlar. Bitta kirish, bitta ma’lumotlar to‘plami, bitta jamoa.",
 "We started from a simple thought: a small company should not pay for five services and move data between them by hand. That is why every part of Firmspace works with the same customers and the same documents as the rest — an invoice already knows its deal, a task already knows its customer.": "Biz oddiy fikrdan boshladik: kichik kompaniya beshta xizmat uchun to‘lamasligi va ular o‘rtasida ma’lumotlarni qo‘lda ko‘chirmasligi kerak. Shuning uchun Firmspace ning har bir qismi qolganlari bilan bir xil mijozlar va bir xil hujjatlar bilan ishlaydi — hisob-faktura o‘z bitimini allaqachon biladi, vazifa o‘z mijozini allaqachon biladi.",
 "We work with German care: invoices follow §14 UStG, reports include UStVA and EÜR, every action stays in the log, data is stored in Germany. And we try hard to make the system understandable without training — hints instead of instructions.": "Biz nemischa puxtalik bilan ishlaymiz: hisob-fakturalar §14 UStG ga amal qiladi, hisobotlar UStVA va EÜR ni o‘z ichiga oladi, har bir harakat jurnalda qoladi, ma’lumotlar Germaniyada saqlanadi. Tizimni o‘qitishsiz tushunarli qilishga ham harakat qilamiz — yo‘riqnoma o‘rniga maslahatlar.",
 "All in one": "Hammasi bir joyda",
 "Deals, conversations, tasks and invoices — without switching between programs.": "Bitimlar, suhbatlar, vazifalar va hisob-fakturalar — dasturlar o‘rtasida almashmasdan.",
 "Clear without training": "O‘qitishsiz tushunarli",
 "The cabinet opens and works: the interface explains itself instead of demanding a manual.": "Kabinet ochiladi va ishlaydi: interfeys qo‘llanma talab qilmasdan o‘zini tushuntiradi.",
 "German accuracy": "Nemischa aniqlik",
 "Invoices under §14 UStG, UStVA and EÜR reports, an action log for every change.": "§14 UStG bo‘yicha hisob-fakturalar, UStVA va EÜR hisobotlari, har bir o‘zgarish uchun harakatlar jurnali.",
 "Data under control": "Ma’lumotlar nazoratda",
 "Storage in Germany, access by role, export of your data at any time.": "Germaniyada saqlash, rol bo‘yicha kirish, ma’lumotlaringizni istalgan vaqtda eksport qilish.",
 "This is what the cabinet looks like — the same layout you get after signing in.": "Kabinet shunday ko‘rinadi — tizimga kirgandan keyin aynan shu ko‘rinishni olasiz.",
 "Our Services": "Xizmatlarimiz",
 "Customer Data Management": "Mijoz ma’lumotlarini boshqarish",
 "One card for every contact and company: history, notes, deals and files in one place.": "Har bir kontakt va kompaniya uchun bitta kartochka: tarix, izohlar, bitimlar va fayllar bir joyda.",
 "Sales Automation": "Savdoni avtomatlashtirish",
 "A visual deals pipeline with stages, reminders and rules that move deals forward for you.": "Bosqichlar, eslatmalar va bitimlarni siz uchun oldinga siljitadigan qoidalar bilan ko‘rgazmali bitimlar voronkasi.",
 "Customer Support and Service": "Mijozlarni qo‘llab-quvvatlash va xizmat ko‘rsatish",
 "Answer customers from one inbox: chat, SMS, calls, Telegram, Viber, Messenger and e-mail.": "Mijozlarga bitta pochta qutisidan javob bering: chat, SMS, qo‘ng‘iroqlar, Telegram, Viber, Messenger va e-pochta.",
 "Marketing Campaign Management": "Marketing kampaniyalarini boshqarish",
 "Plan campaigns, ads and segments, and see which channels bring the customers.": "Kampaniyalar, reklama va segmentlarni rejalashtiring hamda qaysi kanallar mijoz keltirishini ko‘ring.",
 "Analytics and Reporting": "Tahlil va hisobotlar",
 "Dashboards for deals, tasks and team activity — clear numbers instead of guesses.": "Bitimlar, vazifalar va jamoa faolligi bo‘yicha panellar — taxmin o‘rniga aniq raqamlar.",
 "Integration and Mobility": "Integratsiya va harakatchanlik",
 "Connect telephony, mail and messengers, and work from any device with a responsive interface.": "Telefoniya, pochta va messenjerlarni ulang hamda moslashuvchan interfeys bilan istalgan qurilmadan ishlang.",
 "Blog": "Blog",
 "Read More": "Batafsil o‘qish",
 "Back to blog": "Blogga qaytish",
 "Contact": "Aloqa",
 "Feel Free To Ask Us Any Question !": "Bizga istalgan savolni bering!",
 "Name": "Ism",
 "E-Mail": "E-pochta",
 "Phone": "Telefon",
 "Message": "Xabar",
 "Type Your Name Here...": "Ismingizni kiriting...",
 "Type Your Mail Here...": "E-pochtangizni kiriting...",
 "Type Your Phone Here...": "Telefon raqamingizni kiriting...",
 "Type Your Message Here...": "Xabaringizni kiriting...",
 "Send Message": "Xabar yuborish",
 "Sending...": "Yuborilmoqda...",
 "Thank you! We received your message and will answer soon.": "Rahmat! Xabaringizni oldik va tez orada javob beramiz.",
 "The message was not sent. Please check the fields and try again.": "Xabar yuborilmadi. Maydonlarni tekshirib, qayta urinib ko‘ring.",
 "E-mail": "E-pochta",
 "Address": "Manzil",
 "Privacy policy": "Maxfiylik siyosati",
 "1. Who we are": "1. Biz kimmiz",
 "Firmspace AI is a customer relationship management service. This policy explains what personal data we process and why.": "Firmspace AI — mijozlar bilan munosabatlarni boshqarish xizmati. Ushbu siyosat qanday shaxsiy ma'lumotlarni qayta ishlashimiz va nima uchunligini tushuntiradi.",
 "2. Data we collect": "2. Biz to'playdigan ma'lumotlar",
 "Account data (name, e-mail, company), the content you add to the CRM (contacts, deals, tasks, messages) and technical data such as browser type and language.": "Hisob ma'lumotlari (ism, e-pochta, kompaniya), CRMga qo'shgan kontentingiz (kontaktlar, bitimlar, vazifalar, xabarlar) hamda brauzer turi va tili kabi texnik ma'lumotlar.",
 "3. How we use it": "3. Ulardan qanday foydalanamiz",
 "To provide and improve the service, to keep your account secure, to answer your requests and to send important service messages.": "Xizmatni taqdim etish va yaxshilash, hisobingiz xavfsizligini ta'minlash, so'rovlaringizga javob berish va muhim xizmat xabarlarini yuborish uchun.",
 "4. Connected services": "4. Ulangan xizmatlar",
 "When you connect Twilio, Telegram, Viber, Messenger or a mailbox, we store the access keys encrypted and use them only to send and receive messages on your behalf.": "Twilio, Telegram, Viber, Messenger yoki pochta qutisini ulaganingizda, kirish kalitlarini shifrlangan holda saqlaymiz va ulardan faqat sizning nomingizdan xabarlar yuborish va qabul qilish uchun foydalanamiz.",
 "5. Sharing": "5. Ulashish",
 "We do not sell your data. We share it only with infrastructure providers needed to run the service (hosting, database) and when the law requires it.": "Biz ma'lumotlaringizni sotmaymiz. Ularni faqat xizmatni ishlatish uchun zarur bo'lgan infratuzilma provayderlari (xosting, ma'lumotlar bazasi) bilan va qonun talab qilganda ulashamiz.",
 "6. Security": "6. Xavfsizlik",
 "Data is transferred over HTTPS, passwords are stored as hashes and access to the database is restricted.": "Ma'lumotlar HTTPS orqali uzatiladi, parollar xesh ko'rinishida saqlanadi va ma'lumotlar bazasiga kirish cheklangan.",
 "7. Your rights": "7. Sizning huquqlaringiz",
 "You can access, correct, export or delete your data. Write to hello@firmspace.example and we will respond within 30 days.": "Ma'lumotlaringizni ko'rishingiz, tuzatishingiz, eksport qilishingiz yoki o'chirishingiz mumkin. hello@firmspace.example manziliga yozing — 30 kun ichida javob beramiz.",
 "8. Changes": "8. O'zgarishlar",
 "If we change this policy, we will publish the new version on this page.": "Agar ushbu siyosatni o'zgartirsak, yangi versiyani shu sahifada e'lon qilamiz.",
 "Legal notice (Impressum)": "Huquqiy ma'lumot (Impressum)",
 "Template — every value in [brackets] is a placeholder. Replace them with your company's real registration details before publishing this page.": "Shablon — [qavs] ichidagi har bir qiymat to'ldiruvchi. Sahifani nashr qilishdan oldin ularni kompaniyangizning haqiqiy ro'yxatga olish ma'lumotlari bilan almashtiring.",
 "Information pursuant to § 5 TMG": "§ 5 TMG bo'yicha ma'lumot",
 "[Your Company Legal Name] GmbH\n[Street and house number]\n[Postal code] [City], [Country]": "[Kompaniyangizning yuridik nomi] GmbH\n[Ko'cha va uy raqami]\n[Pochta indeksi] [Shahar], [Mamlakat]",
 "Represented by": "Vakil",
 "Managing director: [Full name]": "Boshqaruvchi direktor: [To'liq ism]",
 "Phone: [+49 XX XXXXXXXX]\nE-mail: [legal@yourcompany.example]": "Telefon: [+49 XX XXXXXXXX]\nE-pochta: [legal@yourcompany.example]",
 "Commercial register": "Savdo reestri",
 "Registration court: [Amtsgericht ...]\nRegistration number: [HRB XXXXX]": "Ro'yxatga olish sudi: [Amtsgericht ...]\nRo'yxatga olish raqami: [HRB XXXXX]",
 "VAT identification number": "QQS identifikatsiya raqami",
 "VAT ID according to §27a of the German VAT act: [DE XXXXXXXXX]": "Germaniya QQS qonunining §27a bo'yicha QQS raqami: [DE XXXXXXXXX]",
 "Responsible for content (§ 18 Abs. 2 MStV)": "Kontent uchun mas'ul (§ 18 Abs. 2 MStV)",
 "[Full name]\n[Same address as above]": "[To'liq ism]\n[Yuqoridagi kabi manzil]",
 "Dispute resolution": "Nizolarni hal qilish",
 "The European Commission provides a platform for online dispute resolution (OS): https://ec.europa.eu/consumers/odr/. We are not willing or obliged to participate in dispute resolution proceedings before a consumer arbitration board.": "Yevropa Komissiyasi nizolarni onlayn hal qilish (OS) platformasini taqdim etadi: https://ec.europa.eu/consumers/odr/. Biz iste'molchi arbitraj kengashi oldidagi nizolarni hal qilish jarayonlarida ishtirok etishga tayyor yoki majbur emasmiz.",
 "Liability for content and links": "Kontent va havolalar uchun javobgarlik",
 "As a service provider, we are responsible for our own content on these pages under general law. We are not obliged to monitor transmitted or stored third-party information. Our site may contain links to external websites; we have no influence on their content and assume no liability for it.": "Xizmat provayderi sifatida biz ushbu sahifalardagi o'z kontentimiz uchun umumiy qonunchilikka muvofiq javobgarmiz. Uchinchi shaxslarning uzatilgan yoki saqlangan ma'lumotlarini kuzatishga majbur emasmiz. Saytimizda tashqi veb-saytlarga havolalar bo'lishi mumkin; ularning mazmuniga ta'sir qila olmaymiz va ular uchun javobgarlikni o'z zimmamizga olmaymiz.",
 "Terms and conditions (AGB)": "Foydalanish shartlari (AGB)",
 "Template — replace [bracketed] placeholders with your real company details, and have the payment/cancellation/liability sections reviewed by a lawyer before publishing.": "Shablon — [qavs] ichidagi to'ldiruvchilarni kompaniyangizning haqiqiy ma'lumotlari bilan almashtiring hamda to'lov, bekor qilish va javobgarlik bo'limlarini nashr qilishdan oldin yurist bilan tekshiring.",
 "Last updated: September 2026": "Oxirgi yangilanish: 2026-yil sentabr",
 "1. Scope": "1. Qamrov",
 "These terms apply to all contracts between [Your Company Legal Name] GmbH (\"we\", \"us\") and its customers (\"you\") for the use of the Firmspace AI software as a service.": "Ushbu shartlar [Kompaniyangizning yuridik nomi] GmbH («biz») va uning mijozlari («siz») o'rtasida Firmspace AI dasturiy ta'minotidan xizmat sifatida foydalanish bo'yicha barcha shartnomalarga qo'llanadi.",
 "2. Contract conclusion": "2. Shartnoma tuzish",
 "A contract is concluded when you complete registration and, for paid plans, when payment is confirmed by our payment provider.": "Shartnoma siz ro'yxatdan o'tishni yakunlaganingizda, pullik tariflar uchun esa to'lov provayderimiz tomonidan tasdiqlanganda tuziladi.",
 "3. Plans and pricing": "3. Tariflar va narxlar",
 "Current plans and prices are shown on the Pricing page. Prices are in EUR [plus statutory VAT / already include VAT — confirm which applies in your country]. We may change prices for future billing periods with [30] days' notice.": "Joriy tariflar va narxlar Narxlar sahifasida ko'rsatilgan. Narxlar EURda [qonuniy QQS qo'shilgan holda / QQSni allaqachon o'z ichiga oladi — mamlakatingizda qaysi biri amal qilishini tasdiqlang]. Kelgusi hisob-kitob davrlari uchun narxlarni [30] kun oldin ogohlantirish bilan o'zgartirishimiz mumkin.",
 "4. Payment and billing": "4. To'lov va hisob-kitob",
 "Paid plans are billed monthly or yearly in advance via our payment provider (card, SEPA and other methods it offers). Subscriptions renew automatically until cancelled.": "Pullik tariflar to'lov provayderimiz orqali (karta, SEPA va u taklif qiladigan boshqa usullar) har oy yoki yil oldindan hisoblanadi. Obunalar bekor qilinmaguncha avtomatik ravishda yangilanadi.",
 "5. Cancellation and right of withdrawal": "5. Bekor qilish va voz kechish huquqi",
 "You can cancel a paid plan at any time in Upgrade Your Plan; it stays active until the end of the paid period. Consumers in the EU have a 14-day right of withdrawal from the contract date, unless you have expressly requested immediate access and acknowledged the loss of that right. [Confirm exact wording with a lawyer for your country.]": "Pullik tarifni istalgan vaqtda «Tarifni yangilash» bo'limida bekor qilishingiz mumkin; u to'langan davr oxirigacha faol qoladi. Yevropa Ittifoqidagi iste'molchilar shartnoma sanasidan boshlab 14 kunlik voz kechish huquqiga ega, agar siz darhol kirishni aniq talab qilmagan va bu huquqdan mahrum bo'lishni tasdiqlamagan bo'lsangiz. [Aniq matnni mamlakatingiz uchun yurist bilan tasdiqlang.]",
 "6. Your data and content": "6. Sizning ma'lumotlaringiz va kontentingiz",
 "You retain ownership of all data you enter into the CRM. We process it as described in our Privacy policy and only to provide the service to you.": "CRMga kiritgan barcha ma'lumotlaringizga egalik huquqi sizda qoladi. Biz ularni Maxfiylik siyosatida tavsiflanganidek va faqat sizga xizmat ko'rsatish uchun qayta ishlaymiz.",
 "7. Availability and support": "7. Mavjudlik va qo'llab-quvvatlash",
 "We aim for high availability but do not guarantee uninterrupted service. Planned maintenance is announced in advance where possible. Support is available as described on the Support page.": "Biz yuqori mavjudlikka intilamiz, lekin uzluksiz xizmatni kafolatlamaymiz. Rejalashtirilgan texnik xizmat imkon qadar oldindan e'lon qilinadi. Qo'llab-quvvatlash Yordam sahifasida tavsiflanganidek mavjud.",
 "8. Liability": "8. Javobgarlik",
 "We are liable without limitation for intent and gross negligence, and for injury to life, body or health. For slight negligence, we are liable only for breach of a material contractual obligation, limited to foreseeable, typical damage. [Have this clause reviewed by a lawyer — liability limitations are strictly regulated under German law.]": "Biz qasddan va qo'pol ehtiyotsizlik uchun hamda hayot, tana yoki sog'liqqa yetkazilgan zarar uchun cheklovsiz javobgarmiz. Yengil ehtiyotsizlik uchun faqat muhim shartnoma majburiyatini buzganlik uchun, oldindan ko'rish mumkin bo'lgan odatiy zarar bilan cheklangan holda javobgarmiz. [Ushbu bandni yurist bilan tekshiring — javobgarlikni cheklash Germaniya qonunchiligi bo'yicha qat'iy tartibga solinadi.]",
 "9. Governing law and jurisdiction": "9. Amaldagi qonun va yurisdiksiya",
 "These terms are governed by the law of [Germany / your country], excluding the UN Convention on Contracts for the International Sale of Goods. [Jurisdiction clauses against consumers are restricted by law — confirm with a lawyer.]": "Ushbu shartlar [Germaniya / mamlakatingiz] qonuni bilan tartibga solinadi, Xalqaro tovarlar oldi-sotdisi shartnomalari bo'yicha BMT konvensiyasi bundan mustasno. [Iste'molchilarga qarshi yurisdiksiya bandlari qonun bilan cheklangan — yurist bilan tasdiqlang.]",
 "10. Changes to these terms": "10. Ushbu shartlarga o'zgartirishlar",
 "We may update these terms to reflect changes to the service or the law. We will notify active customers of material changes by e-mail at least [30] days before they take effect.": "Xizmat yoki qonunchilikdagi o'zgarishlarni aks ettirish uchun ushbu shartlarni yangilashimiz mumkin. Muhim o'zgarishlar haqida faol mijozlarni kuchga kirishidan kamida [30] kun oldin e-pochta orqali xabardor qilamiz.",
};