// Узбекские тексты страниц сайта: ключ — английский оригинал из content/*.ts (t3), значение — перевод.
// Юридические страницы (политика, условия, импрессум) и документация сюда намеренно не входят: их перевод готовит юрист; для них показывается английский.
export const UZ: Record<string, string> = {
 "Our Team": "Bizning jamoa",
 "A small team of engineers, designers and support specialists who build Firmspace AI and answer your questions every day.": "Firmspace AI ni yaratadigan va savollaringizga har kuni javob beradigan muhandislar, dizaynerlar va qo‘llab-quvvatlash mutaxassislaridan iborat kichik jamoa.",
 "CEO & Co-founder": "Bosh direktor va hammuassis",
 "Builds the vision and makes sure we solve real problems of small companies.": "Qarashni shakllantiradi va kichik kompaniyalarning haqiqiy muammolarini hal qilishimizni ta’minlaydi.",
 "CTO": "Texnik direktor",
 "Leads the platform architecture: performance, security and integrations.": "Platforma arxitekturasini boshqaradi: unumdorlik, xavfsizlik va integratsiyalar.",
 "Head of Design": "Dizayn rahbari",
 "Makes complex workflows feel simple on every screen size.": "Murakkab ish jarayonlarini har qanday ekran o‘lchamida oddiy qilib ko‘rsatadi.",
 "Senior Engineer": "Yetakchi muhandis",
 "Works on real-time messaging, telephony and mail synchronization.": "Real vaqtdagi xabarlar, telefoniya va pochta sinxronlashi ustida ishlaydi.",
 "Customer Success": "Mijozlar muvaffaqiyati",
 "Helps teams get started and get the most out of the CRM.": "Jamoalarga boshlashga va CRMdan maksimal foydalanishga yordam beradi.",
 "Marketing Lead": "Marketing rahbari",
 "Tells the story of Firmspace AI and listens to what customers need.": "Firmspace AI haqida hikoya qiladi va mijozlarga nima kerakligini tinglaydi.",
 "Careers": "Vakansiyalar",
 "We are growing. Join a friendly remote-first team and help thousands of companies work better with their customers.": "Biz o‘sib bormoqdamiz. Do‘stona masofaviy jamoaga qo‘shiling va minglab kompaniyalarga mijozlari bilan yaxshiroq ishlashga yordam bering.",
 "Why work with us": "Nima uchun biz bilan ishlash kerak",
 "Remote-first with flexible hours": "Masofaviy ish va moslashuvchan jadval",
 "Learning budget and paid conferences": "O‘qish byudjeti va to‘lanadigan konferensiyalar",
 "30 days of paid vacation": "30 kunlik pullik ta’til",
 "Modern stack: Next.js, TypeScript, MongoDB": "Zamonaviy stek: Next.js, TypeScript, MongoDB",
 "Open positions": "Ochiq vakansiyalar",
 "Apply": "Ariza berish",
 "Senior Frontend Engineer": "Katta frontend-muhandis",
 "Remote · Full-time": "Masofaviy · To‘liq stavka",
 "Backend Engineer (Node.js)": "Backend-muhandis (Node.js)",
 "Product Designer": "Mahsulot dizayneri",
 "Berlin or remote · Full-time": "Berlin yoki masofaviy · To‘liq stavka",
 "Customer Support Specialist": "Mijozlarni qo‘llab-quvvatlash mutaxassisi",
 "Remote · Part-time": "Masofaviy · Qisman band",
 "Support / FAQ": "Yordam / Savollar",
 "Answers to the questions we hear most often. Can't find yours? Write to us — we reply within one business day.": "Eng ko‘p so‘raladigan savollarga javoblar. O‘zingiznikini topmadingizmi? Bizga yozing — bir ish kuni ichida javob beramiz.",
 "Contact support": "Yordamga murojaat",
 "How do I create an account?": "Hisobni qanday yarataman?",
 "Press Sign Up in the top right corner, choose Company or Personal, fill in the form and confirm. You can start using the CRM right away.": "Yuqori o‘ng burchakdagi «Ro‘yxatdan o‘tish» tugmasini bosing, «Kompaniya» yoki «Shaxsiy» ni tanlang, shaklni to‘ldiring va tasdiqlang. CRMdan darhol foydalanishni boshlashingiz mumkin.",
 "Is there a free plan?": "Bepul tarif bormi?",
 "Yes, but a limited one: Free covers one user with the sales pipeline and tasks. The team part — employees and knowledge base, the feed and the calendar — starts with Standard at €20 a month (up to 50 users). Chat with customers, documents, finance, marketing, ads, automation and the AI assistant come with Professional at €53 a month, which also removes the user limit.": "Ha, lekin cheklangan: Bepul tarif savdo voronkasi va vazifalar bilan bitta foydalanuvchini qamrab oladi. Jamoa qismi — xodimlar va bilimlar bazasi, lenta va kalendar — Standart tarifdan (oyiga 20 €, 50 tagacha foydalanuvchi) boshlanadi. Mijozlar bilan chat, hujjatlar, moliya, marketing, reklama, avtomatlashtirish va SI yordamchi oyiga 53 € turadigan Professional tarifda, u foydalanuvchilar chegarasini ham olib tashlaydi.",
 "Can I change or cancel my plan?": "Tarifni o‘zgartirish yoki bekor qilish mumkinmi?",
 "Yes, at any time in Upgrade Your Plan. The change applies from the next billing period.": "Ha, istalgan vaqtda «Tarifni yangilash» bo‘limida. O‘zgarish keyingi hisob davridan boshlab kuchga kiradi.",
 "How do I connect Telegram, Viber or a phone number?": "Telegram, Viber yoki telefon raqamini qanday ulayman?",
 "Open Settings → Integration, choose the channel, enter the key from the provider and press Connect. Step-by-step guides are in the Documentation.": "Sozlamalar → Integratsiya bo‘limini oching, kanalni tanlang, provayderdan olingan kalitni kiriting va «Ulash» tugmasini bosing. Bosqichma-bosqich qo‘llanmalar Hujjatlarda.",
 "My mailbox will not connect. What should I do?": "Pochta qutim ulanmayapti. Nima qilay?",
 "Gmail, iCloud and Yahoo need an app password instead of your account password. Create one in your account security settings and use it in Web Mails.": "Gmail, iCloud va Yahoo uchun hisob parolingiz o‘rniga ilova paroli kerak. Uni hisobingiz xavfsizlik sozlamalarida yarating va Veb-pochtada foydalaning.",
 "Is my data safe?": "Ma’lumotlarim xavfsizmi?",
 "Data is transferred over HTTPS, passwords are hashed, and access keys of connected services are stored encrypted.": "Ma’lumotlar HTTPS orqali uzatiladi, parollar xeshlanadi, ulangan xizmatlarning kirish kalitlari shifrlangan holda saqlanadi.",
 "Can I use the CRM on my phone?": "CRMdan telefonda foydalansa bo‘ladimi?",
 "Yes. The interface adapts to phones and tablets, and calls and chats work in the mobile browser.": "Ha. Interfeys telefon va planshetlarga moslashadi, qo‘ng‘iroqlar va chatlar mobil brauzerda ishlaydi.",
 "How do I export my data?": "Ma’lumotlarimni qanday eksport qilaman?",
 "Contact support and we will send you an export of your contacts, companies and deals.": "Yordamga murojaat qiling — kontaktlar, kompaniyalar va bitimlaringiz eksportini yuboramiz.",
 "Features": "Imkoniyatlar",
 "Everything a growing company needs to work with customers, in one place.": "O‘sib borayotgan kompaniyaga mijozlar bilan ishlash uchun kerak bo‘lgan hamma narsa bir joyda.",
 "Deals pipeline": "Bitimlar voronkasi",
 "Kanban board with custom stages, drag and drop, comments and activity history.": "O‘zingiz belgilagan bosqichlar, sudrab o‘tkazish, izohlar va faollik tarixi bilan kanban doskasi.",
 "Contacts and companies": "Kontaktlar va kompaniyalar",
 "Complete cards with notes, links between people and companies, and search.": "Izohlar, odamlar va kompaniyalar o‘rtasidagi bog‘lanishlar hamda qidiruv bilan to‘liq kartochkalar.",
 "Tasks and calendar": "Vazifalar va kalendar",
 "Deadlines, reminders and a shared company calendar with week and month views.": "Muddatlar, eslatmalar va hafta hamda oy ko‘rinishlari bilan umumiy kompaniya kalendari.",
 "Unified inbox": "Yagona pochta qutisi",
 "Telegram, Viber, Messenger, SMS and website chat answered from one page.": "Telegram, Viber, Messenger, SMS va veb-sayt chati — bitta sahifadan javob beriladi.",
 "Calls in the browser": "Brauzerda qo‘ng‘iroqlar",
 "Call customers and receive calls through Twilio with a full call log.": "Twilio orqali mijozlarga qo‘ng‘iroq qiling va qo‘ng‘iroqlarni qabul qiling, to‘liq qo‘ng‘iroqlar jurnali bilan.",
 "Web mail": "Veb-pochta",
 "Gmail, Outlook, iCloud, Yahoo or any IMAP mailbox with drafts, stars and search.": "Gmail, Outlook, iCloud, Yahoo yoki istalgan IMAP pochta qutisi — qoralamalar, belgilar va qidiruv bilan.",
 "Automation": "Avtomatlashtirish",
 "Rules that react to stages, variables and constants — fewer manual steps.": "Bosqichlar, o‘zgaruvchilar va doimiylarga javob beradigan qoidalar — qo‘lda bajariladigan qadamlar kamroq.",
 "Marketing tools": "Marketing vositalari",
 "Campaigns, ads, segments and templates with results in one table.": "Kampaniyalar, reklama, segmentlar va shablonlar, natijalar bitta jadvalda.",
 "Inventory management": "Ombor boshqaruvi",
 "Stock, sales, transfers and write-offs, connected to your customers.": "Zaxira, sotuvlar, ko‘chirishlar va hisobdan chiqarishlar mijozlaringiz bilan bog‘langan.",
 "Referral program": "Referal dasturi",
 "Recommend Firmspace AI to other companies and get a free month for every company that subscribes.": "Firmspace AI ni boshqa kompaniyalarga tavsiya qiling va obuna bo‘lgan har bir kompaniya uchun bepul bir oy oling.",
 "How it works": "Qanday ishlaydi",
 "Share your link": "Havolangizni ulashing",
 "Send your personal link to a colleague, partner or client.": "Shaxsiy havolangizni hamkasb, hamkor yoki mijozga yuboring.",
 "They subscribe": "Ular obuna bo‘ladi",
 "The company signs up and chooses the Standard or Professional plan.": "Kompaniya ro‘yxatdan o‘tadi va Standart yoki Professional tarifni tanlaydi.",
 "You both win": "Ikkalangiz ham yutasiz",
 "You get one free month, and the new company gets 10% off its first year.": "Siz bir oy bepul olasiz, yangi kompaniya esa birinchi yilga 10% chegirma oladi.",
 "Your referral link": "Referal havolangiz",
 "Copy link": "Havolani nusxalash",
 "Copied!": "Nusxalandi!",
 "Sign in to get your personal link. Rewards are credited after the first payment of the invited company.": "Shaxsiy havolangizni olish uchun tizimga kiring. Mukofotlar taklif qilingan kompaniyaning birinchi to‘lovidan keyin hisoblanadi.",
 "About us": "Biz haqimizda",
 "Firmspace AI brings customer relationships, team work, projects and accounting into one cabinet. We build it for small and medium businesses — those where one person often does several jobs at once.": "Firmspace AI mijozlar bilan munosabatlar, jamoaviy ish, loyihalar va buxgalteriyani bitta kabinetga birlashtiradi. Biz uni kichik va o‘rta biznes uchun yaratamiz — bir kishi ko‘pincha bir vaqtning o‘zida bir nechta ishni bajaradigan biznes uchun.",
 "Our team at work": "Jamoamiz ish joyida",
 "We collect in one place what is usually scattered across five programs: the deal pipeline, conversations with customers, tasks and the calendar, quotes, orders, invoices and reports. One login, one set of data, one team.": "Odatda beshta dasturga tarqalgan narsani bir joyga yig‘amiz: bitimlar voronkasi, mijozlar bilan suhbatlar, vazifalar va kalendar, takliflar, buyurtmalar, hisob-fakturalar va hisobotlar. Bitta kirish, bitta ma’lumotlar to‘plami, bitta jamoa.",
 "We started from a simple thought: a small company should not pay for five services and move data between them by hand. That is why every part of Firmspace works with the same customers and the same documents as the rest — an invoice already knows its deal, a task already knows its customer.": "Biz oddiy fikrdan boshladik: kichik kompaniya beshta xizmat uchun to‘lamasligi va ular o‘rtasida ma’lumotlarni qo‘lda ko‘chirmasligi kerak. Shuning uchun Firmspace ning har bir qismi qolganlari bilan bir xil mijozlar va bir xil hujjatlar bilan ishlaydi — hisob-faktura o‘z bitimini allaqachon biladi, vazifa o‘z mijozini allaqachon biladi.",
 "We work with German care: invoices follow §14 UStG, reports include UStVA and EÜR, every action stays in the log, data is stored in Germany. And we try hard to make the system understandable without training — hints instead of instructions.": "Biz nemischa puxtalik bilan ishlaymiz: hisob-fakturalar §14 UStG ga amal qiladi, hisobotlar UStVA va EÜR ni o‘z ichiga oladi, har bir harakat jurnalda qoladi, ma’lumotlar Germaniyada saqlanadi. Tizimni o‘qitishsiz tushunarli qilishga ham harakat qilamiz — yo‘riqnoma o‘rniga maslahatlar.",
 "All in one": "Hammasi bir joyda",
 "Deals, conversations, tasks and invoices — without switching between programs.": "Bitimlar, suhbatlar, vazifalar va hisob-fakturalar — dasturlar o‘rtasida almashmasdan.",
 "Clear without training": "O‘qitishsiz tushunarli",
 "The cabinet opens and works: the interface explains itself instead of demanding a manual.": "Kabinet ochiladi va ishlaydi: interfeys qo‘llanma talab qilmasdan o‘zini tushuntiradi.",
 "German accuracy": "Nemischa aniqlik",
 "Invoices under §14 UStG, UStVA and EÜR reports, an action log for every change.": "§14 UStG bo‘yicha hisob-fakturalar, UStVA va EÜR hisobotlari, har bir o‘zgarish uchun harakatlar jurnali.",
 "Data under control": "Ma’lumotlar nazoratda",
 "Storage in Germany, access by role, export of your data at any time.": "Germaniyada saqlash, rol bo‘yicha kirish, ma’lumotlaringizni istalgan vaqtda eksport qilish.",
 "This is what the cabinet looks like — the same layout you get after signing in.": "Kabinet shunday ko‘rinadi — tizimga kirgandan keyin aynan shu ko‘rinishni olasiz.",
 "Our Services": "Xizmatlarimiz",
 "Customer Data Management": "Mijoz ma’lumotlarini boshqarish",
 "One card for every contact and company: history, notes, deals and files in one place.": "Har bir kontakt va kompaniya uchun bitta kartochka: tarix, izohlar, bitimlar va fayllar bir joyda.",
 "Sales Automation": "Savdoni avtomatlashtirish",
 "A visual deals pipeline with stages, reminders and rules that move deals forward for you.": "Bosqichlar, eslatmalar va bitimlarni siz uchun oldinga siljitadigan qoidalar bilan ko‘rgazmali bitimlar voronkasi.",
 "Customer Support and Service": "Mijozlarni qo‘llab-quvvatlash va xizmat ko‘rsatish",
 "Answer customers from one inbox: chat, SMS, calls, Telegram, Viber, Messenger and e-mail.": "Mijozlarga bitta pochta qutisidan javob bering: chat, SMS, qo‘ng‘iroqlar, Telegram, Viber, Messenger va e-pochta.",
 "Marketing Campaign Management": "Marketing kampaniyalarini boshqarish",
 "Plan campaigns, ads and segments, and see which channels bring the customers.": "Kampaniyalar, reklama va segmentlarni rejalashtiring hamda qaysi kanallar mijoz keltirishini ko‘ring.",
 "Analytics and Reporting": "Tahlil va hisobotlar",
 "Dashboards for deals, tasks and team activity — clear numbers instead of guesses.": "Bitimlar, vazifalar va jamoa faolligi bo‘yicha panellar — taxmin o‘rniga aniq raqamlar.",
 "Integration and Mobility": "Integratsiya va harakatchanlik",
 "Connect telephony, mail and messengers, and work from any device with a responsive interface.": "Telefoniya, pochta va messenjerlarni ulang hamda moslashuvchan interfeys bilan istalgan qurilmadan ishlang.",
 "Blog": "Blog",
 "Read More": "Batafsil o‘qish",
 "Back to blog": "Blogga qaytish",
 "Contact": "Aloqa",
 "Feel Free To Ask Us Any Question !": "Bizga istalgan savolni bering!",
 "Name": "Ism",
 "E-Mail": "E-pochta",
 "Phone": "Telefon",
 "Message": "Xabar",
 "Type Your Name Here...": "Ismingizni kiriting...",
 "Type Your Mail Here...": "E-pochtangizni kiriting...",
 "Type Your Phone Here...": "Telefon raqamingizni kiriting...",
 "Type Your Message Here...": "Xabaringizni kiriting...",
 "Send Message": "Xabar yuborish",
 "Sending...": "Yuborilmoqda...",
 "Thank you! We received your message and will answer soon.": "Rahmat! Xabaringizni oldik va tez orada javob beramiz.",
 "The message was not sent. Please check the fields and try again.": "Xabar yuborilmadi. Maydonlarni tekshirib, qayta urinib ko‘ring.",
 "E-mail": "E-pochta",
 "Address": "Manzil"
};
